default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 20 } %>
  username: <%= ENV['COMMENTUI_DATABASE_USERNAME'] %>
  password: <%= ENV['COMMENTUI_DATABASE_PASSWORD'] %>
  host: <%= ENV['COMMENTUI_DATABASE_HOST'] %>
  port: <%= ENV['COMMENTUI_DATABASE_PORT'] %>

development:
  <<: *default
  database: <%= ENV['COMMENTUI_DATABASE_DATABASE_DEV'] %>

test:
  <<: *default
  database: <%= ENV['COMMENTUI_DATABASE_DATABASE_TEST'] %>
