default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 20 } %>
  username: austin
  password: password
  host: localhost
  port: 5432

development:
  <<: *default
  database: commentui_development

test:
  <<: *default
  database: commentui_test
