# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 35abf76a10899e5f86d067a2f1bdb67c0edae255b48d88d57fa78aff94ef3c4eecd32399286ff5272d6c27553eb9e08e221ba17e1283e1b2876b7d389c3ff565

test:
  secret_key_base: b101c63ed032fd5ae9c4aade14561e2ee1027e6e2b68148b85dd34566fc160fac976fee7982941581a9a64b0f76ff59071ca53630250fb215bc7ce64d9b47ae3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
